development: &defaults
  log_level: warn
  assets: &assets_config
    digest: false
    compress: false

test:
  <<: *defaults

production:
  <<: *defaults
  assets:
    <<: *assets_config
    digest: true
    compress: true
